name: CSSS
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - nbconvert
  - notebook
  - tornado
  - matplotlib
  - numpy
  - scipy
  - pandas
  - pycairo
  - python-igraph
  - leidenalg
