channels:
  - vtraag
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - nbconvert=5.4.0
  - notebook=5.7.4
  - tornado<6
  - matplotlib
  - numpy
  - scipy
  - pandas>=0.21.0
  - pycairo
  - python-igraph
  - leidenalg
  - metaknowledge
